.\"    Author: Marcus Wanner <marcus@wanners.net>
.\"  Language: English
.TH NXT_TEST "1" "April 2011" "nxt-python" "nxt-python"
.SH "NAME"
nxt_test \- test the nxt-python setup and brick firmware interaction
.SH "DESCRIPTION"
.P
The
.B nxt_test
command looks for nxt bricks and prints out various statistics about each one. It relies most heavily on the nxt.brick.Brick.get_device_info() function for its data. Running it ensures that the relevant communication subsystem is usable and that the firmware on the brick is talking to nxt-python correctly.
.SH "OPTIONS"
.PP
When run, 
.B nxt_test
doesn't accept any arguments.
