#!/usr/bin/env python3
#
# nxt_push program -- Push a file to a LEGO Mindstorms NXT brick
# Copyright (C) 2006  Douglas P Lau
# Copyright (C) 2010  rhn
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

import argparse
import nxt.locator
from nxt.error import FileNotFound

def _write_file(b, fname, data):
    print('Pushing %s (%d bytes) ...' % (fname, len(data)), end=' ', flush=True)
    with b.open_file(fname, 'wb', len(data)) as w:
        w.write(data)
    print('wrote %d bytes' % len(data))

def write_file(b, fname):
    with open(fname, 'rb') as f:
        data = f.read()
    try:
        b.delete(fname)
        print('Overwriting %s on NXT' % fname)
    except FileNotFound:
        pass
    _write_file(b, fname, data)

if __name__ == '__main__':
    p = argparse.ArgumentParser(
        description="Push files to a LEGO Mindstorms NXT brick")
    p.add_argument("--host", metavar="ADDR", help="brick address")
    p.add_argument("file", nargs="+", help="file to transfer")
    options = p.parse_args()

    brick = nxt.locator.find_one_brick(options.host)
    for filename in options.file:
        write_file(brick, filename)
    brick.sock.close()
