#!/usr/bin/env python3

import argparse
import nxt.locator

p = argparse.ArgumentParser(description="Test the nxt-python setup")
p.add_argument("--debug", action="store_true", default=False, help="enable debugging")
options = p.parse_args()

print('Find brick...', flush=True)
b = nxt.locator.find_one_brick(debug=options.debug)
name, host, signal_strengths, user_flash = b.get_device_info()
print('NXT brick name: %s' % name)
print('Host address: %s' % host)
print('Bluetooth signal strengths: %r' % (signal_strengths,))
print('Free user flash: %s' % user_flash)
prot_version, fw_version = b.get_firmware_version()
print('Protocol version %s.%s' % prot_version)
print('Firmware version %s.%s' % fw_version)
millivolts = b.get_battery_level()
print('Battery level %s mV' % millivolts)
print('Play test sound...', end='', flush=True)
b.play_tone_and_wait(300, 50)
b.play_tone_and_wait(400, 50)
b.play_tone_and_wait(500, 50)
b.play_tone_and_wait(600, 50)
print('done')
b.sock.close()
